### PR TITLE
Update `react-rhino` to latest version

### PR DESCRIPTION
**Pull request by aromalanil**
# Description
If merged, this PR will
- Bump version of `react-rhino` to v2.1.2 and update the codebase accordingly
- This will not break the api, just change the internal code

### CODE REVIEW

**Comment by technikhil314** [comment]
Hey @aromalanil Sorry I just checked your PR. But I have moved to npm from yarn. Can you send me the patch or update the PR. I will merge it.

**Comment by aromalanil** [comment]
@technikhil314 Yeah sure, I'll change it

**Comment by aromalanil** [comment]
@technikhil314 The npm workspaces doesn't seems to work. Is it okay to just update the version in `packages/fontend`

**Comment by aromalanil** [comment]
I have also used the hooks `useSetRhinoState` & `useRhinoValue` where it's appropriate for optimisation

**Pull request merged**
